name: unai_chatbot_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # Shared Preferences (สำหรับ Remember Me)
  shared_preferences: ^2.3.3
  
  # Provider (สำหรับ Theme Management)
  provider: ^6.1.1
  
  # File Picker (สำหรับ Admin Upload)
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/